# yaml-language-server: $schema=./node_modules/@mark-magic/cli/dist/config.schema.json

generate:
  - name: 朱颜血-洁梅
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/01/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-洁梅.epub
        metadata:
          id: book-01
          title: 洁梅
          creator: 浮萍居主
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-夜莲
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/02/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-夜莲.epub
        metadata:
          id: book-01
          title: 夜莲
          creator: 浮萍居主
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-芙蓉
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/03/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-芙蓉.epub
        metadata:
          id: book-01
          title: 芙蓉
          creator: 抱残
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-红棉
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/04/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-红棉.epub
        metadata:
          id: book-01
          title: 红棉
          creator: RKING
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-紫玫
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/05/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-紫玫.epub
        metadata:
          id: book-01
          title: 紫玫
          creator: 紫狂
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-苍兰
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/06/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-苍兰.epub
        metadata:
          id: book-01
          title: 苍兰
          creator: 小悴
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-雪芍
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/07/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-雪芍.epub
        metadata:
          id: book-01
          title: 雪芍
          creator: 紫狂
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-海棠
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/08/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-海棠.epub
        metadata:
          id: book-01
          title: 海棠
          creator: 寒江
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-丹杏
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/09/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-丹杏.epub
        metadata:
          id: book-01
          title: 丹杏
          creator: 紫狂
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-百合
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/10/
    output:
      name: '@mark-magic/plugin-epub'
      config:
        path: dist/epub/朱颜血-百合.epub
        metadata:
          id: book-01
          title: 百合
          creator: 白纸
          publisher: rxliuli
          language: zh-CN
  - name: 朱颜血-网站
    input:
      name: '@mark-magic/plugin-local'
      config:
        path: ./books/
    output:
      name: '@mark-magic/plugin-docs'
      config:
        path: dist/docs
        public: ./public/
        name: 朱颜血
        repo: https://github.com/liuli-moe/ZhuYanXue.git
        theme:
          dark: true
        giscus:
          repo: liuli-moe/ZhuYanXue
          repoId: MDEwOlJlcG9zaXRvcnkxOTcxODk3ODM=
          category: Announcements
          categoryId: DIC_kwDOC8Dgl84CXb9i
          mapping: pathname
          reactionsEnabled: '1'
          emitMetadata: '0'
          inputPosition: bottom
          theme: dark
          lang: zh-CN
          crossorigin: anonymous
